### ISSUE TITLE
Stimulus controller is not connected inside frames

### ISSUE THREAD

**Issue by AxelBriche** [hotwired/hotwire-rails#33] opened 2021-03-31 08:24 UTC
Stimulus controllers are not connected when present inside a turbo-frame, the problem is know?

**Comment by seanpdoyle** [comment] 2021-03-31 14:38
Is this a duplicate of https://github.com/hotwired/stimulus-rails/issues/56?

@AxelBriche could you share more details to help us reproduce the issue?

For instance, could you share a sample of the page's HTML and a sample of Stimulus controller's code?

**Closed** 2021-04-09 12:31 UTC
